language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - TRAVIS_NODE_VERSION="4"

install:
  - pip install pep8
  - npm install

script:
  - pep8 --verbose webassets_webpack
  - make test

sudo: false
